"""Parent-facing rights and resources library (PRD FR-22).

Static, curated, plain-language documents that each cite an official source. Nothing here is
generated by a model, and nothing here is legal advice.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException

from ..auth import Actor, get_actor
from ..storage import store

router = APIRouter(prefix="/resources", tags=["resources"])

LIST_FIELDS = ("id", "category", "title", "summary", "source_org", "source_name",
               "source_url", "citation", "reading_minutes", "key_points")


@router.get("")
def list_resources(actor: Actor = Depends(get_actor)):
    if actor.role == "student":
        raise HTTPException(403, "not permitted")
    return [{k: r[k] for k in LIST_FIELDS} for r in store.read_seed("resources")]


@router.get("/{resource_id}")
def get_resource(resource_id: str, actor: Actor = Depends(get_actor)):
    if actor.role == "student":
        raise HTTPException(403, "not permitted")
    for r in store.read_seed("resources"):
        if r["id"] == resource_id:
            return r
    raise HTTPException(404, "unknown resource")
